/** Static class strings so Tailwind can see them. Assigned to months by index. */
export const MONTH_COLORS = [
  {
    tint: 'border-sky-200 bg-sky-50 text-sky-700',
    active: 'border-sky-600 bg-sky-600 text-white',
    week: 'bg-sky-50 hover:border-sky-400 data-active:border-sky-600 data-active:bg-sky-600',
    panel: 'border-sky-200 bg-sky-50/40',
    header: 'from-sky-600 to-sky-500',
    bar: 'bg-sky-500',
    text: 'text-sky-700',
    chip: 'bg-sky-100 text-sky-800',
  },
  {
    tint: 'border-emerald-200 bg-emerald-50 text-emerald-700',
    active: 'border-emerald-600 bg-emerald-600 text-white',
    week: 'bg-emerald-50 hover:border-emerald-400 data-active:border-emerald-600 data-active:bg-emerald-600',
    panel: 'border-emerald-200 bg-emerald-50/40',
    header: 'from-emerald-600 to-emerald-500',
    bar: 'bg-emerald-500',
    text: 'text-emerald-700',
    chip: 'bg-emerald-100 text-emerald-800',
  },
  {
    tint: 'border-amber-200 bg-amber-50 text-amber-700',
    active: 'border-amber-500 bg-amber-500 text-white',
    week: 'bg-amber-50 hover:border-amber-400 data-active:border-amber-500 data-active:bg-amber-500',
    panel: 'border-amber-200 bg-amber-50/40',
    header: 'from-amber-500 to-amber-400',
    bar: 'bg-amber-500',
    text: 'text-amber-700',
    chip: 'bg-amber-100 text-amber-800',
  },
  {
    tint: 'border-rose-200 bg-rose-50 text-rose-700',
    active: 'border-rose-600 bg-rose-600 text-white',
    week: 'bg-rose-50 hover:border-rose-400 data-active:border-rose-600 data-active:bg-rose-600',
    panel: 'border-rose-200 bg-rose-50/40',
    header: 'from-rose-600 to-rose-500',
    bar: 'bg-rose-500',
    text: 'text-rose-700',
    chip: 'bg-rose-100 text-rose-800',
  },
  {
    tint: 'border-violet-200 bg-violet-50 text-violet-700',
    active: 'border-violet-600 bg-violet-600 text-white',
    week: 'bg-violet-50 hover:border-violet-400 data-active:border-violet-600 data-active:bg-violet-600',
    panel: 'border-violet-200 bg-violet-50/40',
    header: 'from-violet-600 to-violet-500',
    bar: 'bg-violet-500',
    text: 'text-violet-700',
    chip: 'bg-violet-100 text-violet-800',
  },
  {
    tint: 'border-teal-200 bg-teal-50 text-teal-700',
    active: 'border-teal-600 bg-teal-600 text-white',
    week: 'bg-teal-50 hover:border-teal-400 data-active:border-teal-600 data-active:bg-teal-600',
    panel: 'border-teal-200 bg-teal-50/40',
    header: 'from-teal-600 to-teal-500',
    bar: 'bg-teal-500',
    text: 'text-teal-700',
    chip: 'bg-teal-100 text-teal-800',
  },
] as const

export type MonthColor = Record<
  'tint' | 'active' | 'week' | 'panel' | 'header' | 'bar' | 'text' | 'chip',
  string
>

/** Brand-palette colours (primary / secondary / dark / chart tones) for the monthly page. */
export const BRAND_MONTH_COLORS: readonly MonthColor[] = [
  {
    tint: 'border-brand-primary/25 bg-brand-primary/10 text-brand-dark',
    active: 'border-brand-primary bg-brand-primary text-white',
    week: '',
    panel: '',
    header: 'from-brand-primary to-brand-dark',
    bar: 'bg-brand-primary',
    text: 'text-brand-primary',
    chip: 'bg-brand-primary/15 text-brand-primary',
  },
  {
    tint: 'border-brand-secondary/30 bg-brand-secondary/10 text-brand-dark',
    active: 'border-brand-secondary bg-brand-secondary text-white',
    week: '',
    panel: '',
    header: 'from-brand-secondary to-brand-primary',
    bar: 'bg-brand-secondary',
    text: 'text-brand-secondary',
    chip: 'bg-brand-secondary/15 text-brand-dark',
  },
  {
    tint: 'border-brand-dark/25 bg-brand-dark/10 text-brand-dark',
    active: 'border-brand-dark bg-brand-dark text-white',
    week: '',
    panel: '',
    header: 'from-brand-dark to-brand-primary',
    bar: 'bg-brand-dark',
    text: 'text-brand-dark',
    chip: 'bg-brand-dark/15 text-brand-dark',
  },
  {
    tint: 'border-chart-3/30 bg-chart-3/10 text-brand-dark',
    active: 'border-chart-3 bg-chart-3 text-white',
    week: '',
    panel: '',
    header: 'from-chart-3 to-brand-secondary',
    bar: 'bg-chart-3',
    text: 'text-chart-3',
    chip: 'bg-chart-3/15 text-brand-dark',
  },
  {
    tint: 'border-brand-muted bg-brand-light text-brand-dark',
    active: 'border-brand-primary bg-brand-muted text-brand-dark',
    week: '',
    panel: '',
    header: 'from-chart-4 to-chart-3',
    bar: 'bg-chart-5',
    text: 'text-brand-dark',
    chip: 'bg-brand-light text-brand-dark',
  },
]
